#!/bin/bash
#
# Script to fix WSL internet connectivity by setting a static resolv.conf.
# This prevents WSL from losing DNS resolution, especially when using Pi-hole.

echo "🔧 Starting WSL internet connectivity fix..."
LOG_FILE="/tmp/wsl_internet_fix.log"
echo "" > "$LOG_FILE" # Clear log file

log() {
    echo "$1" | tee -a "$LOG_FILE"
}

# Path to the resolv.conf file
RESOLV_CONF="/etc/resolv.conf"

# First, ensure we have sudo access
sudo -v

# Check if the file is immutable
if lsattr -l "$RESOLV_CONF" 2>/dev/null | grep -q "Immutable"; then
    log "📄 Found immutable flag on $RESOLV_CONF. Removing it first..."
    sudo chattr -i "$RESOLV_CONF"
    if [ $? -ne 0 ]; then
        log "❌ ERROR: Failed to remove immutable flag. Please run this script as a user with sudo privileges."
        exit 1
    fi
fi

log "📝 Writing new DNS configuration to $RESOLV_CONF..."
# Using reliable public DNS servers
sudo bash -c "cat > $RESOLV_CONF" <<EOF
# Generated by PiFiller to ensure WSL connectivity
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
options edns0
EOF

if [ $? -ne 0 ]; then
    log "❌ ERROR: Failed to write to $RESOLV_CONF."
    exit 1
fi

log "🔒 Making $RESOLV_CONF immutable to prevent changes..."
sudo chattr +i "$RESOLV_CONF"
if [ $? -ne 0 ]; then
    log "❌ ERROR: Failed to set immutable flag."
    exit 1
fi

log "✅ Successfully secured $RESOLV_CONF."

# Test connectivity
log "🌐 Testing internet connectivity..."
if ping -c 2 google.com &> /dev/null; then
    log "✅ Internet connectivity confirmed."
else
    log "⚠️ WARNING: Could not ping google.com. There might still be a network issue."
fi

log "🎉 WSL internet fix applied successfully!"
exit 0